/**
 * GAME CONFIGURATION
 * Auto-generated by Playable Creator Studio
 */

window.GAME_CONFIG = {
  "cta": {
    "url": "https://google.com",
    "target": "_blank"
  },
  "text": {
    "ctaSize": 36,
    "ctaText": "BUY",
    "endHeading": "",
    "endSubtext": "",
    "gameSubtext": "Tap tiles to slide",
    "instruction": "",
    "endHeadingSize": 40,
    "endSubtextSize": 20,
    "timeoutHeading": "Time's Up!",
    "timeoutSubtext": "Better luck next time!",
    "endHeadingColor": "#deaa32",
    "endSubtextColor": "#deaa32",
    "gameInstruction": "Solve the Puzzle",
    "gameSubtextSize": 18,
    "instructionSize": 36,
    "actionButtonSize": 36,
    "actionButtonText": "PLAY",
    "gameSubtextColor": "#deaa32",
    "instructionColor": "#deaa32",
    "gameInstructionSize": 32,
    "gameInstructionColor": "#deaa32"
  },
  "fonts": {
    "primary": "Poppins",
    "semibold": "Poppins",
    "scaleFactor": 1
  },
  "assets": {
    "logo": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/puzzle_basic_test_47c2b9bb/assets/images/logo.png",
    "endHero": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/puzzle_basic_test_47c2b9bb/assets/images/endHero.png",
    "winSound": "",
    "moveSound": "",
    "splashHero": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/puzzle_basic_test_47c2b9bb/assets/images/splashHero.png",
    "puzzleImage": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/puzzle_basic_test_47c2b9bb/assets/images/puzzleImage.png",
    "backgroundMusic": ""
  },
  "canvas": {
    "width": 640,
    "height": 960,
    "backgroundColor": "#000000"
  },
  "colors": {
    "text": "#645341",
    "primary": "#f9f5e9",
    "confetti": [
      "#645341",
      "#f9f5e9",
      "#8b7355",
      "#a69076"
    ],
    "secondary": "#645341"
  },
  "layout": {
    "logoScale": 0.3,
    "puzzleScale": 0.85,
    "showEndHero": true,
    "logoScaleEnd": 0.3,
    "logoScaleGame": 0.2,
    "logoTopMargin": 0.05,
    "ctaButtonWidth": 400,
    "showSplashHero": true,
    "ctaButtonHeight": 80,
    "puzzleTopMargin": 0.4,
    "endHeroYPosition": 0.6,
    "actionButtonWidth": 400,
    "actionButtonHeight": 80,
    "ctaButtonTopMargin": 0.85,
    "splashHeroYPosition": 0.55,
    "instructionTopMargin": 0.25,
    "actionButtonTopMargin": 0.85,
    "gameInstructionTopMargin": 0.24
  },
  "gameplay": {
    "gridSize": 3,
    "autoEndTimer": false,
    "gameDuration": 30000,
    "tileBorderColor": "#FFFFFF",
    "tileBorderWidth": 2,
    "shuffleIterations": 6
  },
  "scoreBox": {
    "scale": 1,
    "shape": "rounded",
    "textColor": "#f9f5e9",
    "borderColor": "#645341",
    "borderWidth": 0,
    "backgroundColor": "#645341"
  },
  "tracking": {
    "events": {
      "click": {
        "urls": []
      },
      "impression": {
        "urls": []
      },
      "playableStart": {
        "urls": []
      },
      "playableTimeout": {
        "urls": []
      },
      "playableComplete": {
        "urls": []
      }
    }
  },
  "ctaButton": {
    "scale": 1,
    "shape": "rounded",
    "textColor": "#ce3a2f",
    "borderColor": "#deaa32",
    "borderWidth": 0,
    "backgroundColor": "#deaa32"
  },
  "background": {
    "type": "solid",
    "image": "",
    "solidColor": "#ce3a2f",
    "gradientEnd": "#e8e4d9",
    "gradientAngle": 90,
    "gradientStart": "#f9f5e9"
  },
  "loadingBar": {
    "width": 250,
    "height": 20,
    "fillColor": "#645341",
    "backgroundColor": "#d9d5ca"
  },
  "transition": {
    "fade": {
      "alpha": 0.8,
      "color": 0
    },
    "type": "confetti",
    "confetti": {
      "bursts": 3,
      "origin": {
        "y": 0.6
      },
      "spread": 100,
      "burstDelay": 200,
      "particleCount": 100
    },
    "duration": 3000
  },
  "_editorMode": "basic",
  "assetScales": {
    "logo": 1.9,
    "endHero": 1.1,
    "background": 1,
    "splashHero": 1.5,
    "puzzleImage": 1
  },
  "actionButton": {
    "scale": 1,
    "shape": "rounded",
    "textColor": "#ce3a2f",
    "borderColor": "#deaa32",
    "borderWidth": 0,
    "backgroundColor": "#deaa32"
  },
  "firstPartyData": {
    "enabled": false,
    "screens": {
      "age": false,
      "email": false,
      "gender": false
    },
    "placement": null,
    "emailPromptText": "Enter your email for updates"
  }
};
