/**
 * GAME CONFIGURATION
 * Auto-generated by Playable Creator Studio
 */

window.GAME_CONFIG = {
  "cta": {
    "url": "https://www.iion.com",
    "target": "_blank"
  },
  "text": {
    "ctaSize": 38,
    "ctaText": "Know More",
    "scoreSize": 40,
    "howToTitle": "You made it!",
    "scoreColor": "#FFFFFF",
    "howToAction": "TAP TO START",
    "instruction": "get ready for the race",
    "scoreFormat": "{score}",
    "howToMessage": "Come visit, participate and have a chance\nto be at the race in Zandvoort!",
    "endScreenText": "Experience game advertising\nlike never before.",
    "howToTitleSize": 50,
    "howToActionSize": 36,
    "howToTitleColor": "#FFFFFF",
    "instructionSize": 45,
    "actionButtonSize": 38,
    "actionButtonText": "Start your engines",
    "howToActionColor": "#FFFFFF",
    "howToInstruction": "Swipe left or right to avoid obstacles\nand collect Shell V-Power coins",
    "howToMessageSize": 32,
    "instructionColor": "#FFFFFF",
    "endScreenTextSize": 40,
    "howToMessageColor": "#FFFFFF",
    "endScreenTextColor": "#FFFFFF",
    "howToInstructionSize": 28,
    "howToInstructionColor": "#FFFFFF"
  },
  "fonts": {
    "ctaSize": 24,
    "primary": "Poppins",
    "semibold": "Poppins",
    "scoreSize": 40,
    "scaleFactor": 1.4,
    "instructionSize": 45,
    "actionButtonSize": 32
  },
  "assets": {
    "logo": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/lane-racer-logo.png",
    "road": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/road.png",
    "endHero": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/endHero.png",
    "obstacle": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/car2.png",
    "scoreBox": "",
    "character": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/car1.png",
    "finishLine": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/finishline.png",
    "splashHero": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/splashHero.png",
    "collectible": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/coin.png",
    "collectSound": "",
    "backgroundMusic": "",
    "age1": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/fpd/age1.png",
    "age2": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/fpd/age2.png",
    "age3": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/fpd/age3.png",
    "age4": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/fpd/age4.png",
    "age5": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/fpd/age5.png",
    "age6": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/fpd/age6.png",
    "genderMale": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/fpd/genderMale.png",
    "genderFemale": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/fpd/genderFemale.png",
    "genderOthers": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/fpd/genderOthers.png",
    "dataCaptureBg": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/lane_racer_fix_test_249d84e1/assets/images/fpd/background.png"
  },
  "canvas": {
    "width": 960,
    "height": 1440,
    "backgroundColor": "#0009ff"
  },
  "colors": {
    "text": "#FFFFFF",
    "primary": "#FBCE0C",
    "confetti": [
      "#FBCE0C",
      "#DD2024",
      "#FFFFFF",
      "#F9B700"
    ],
    "scoreText": "#DD2024",
    "secondary": "#DD2024",
    "loadingBar": "#FBCE0C"
  },
  "layout": {
    "logoScale": 0.6,
    "scaleFactor": 1.4,
    "showEndHero": true,
    "logoScaleEnd": 0.6,
    "logoScaleGame": 0.3,
    "logoTopMargin": 0.12,
    "scoreBoxScale": 1,
    "ctaButtonWidth": 280,
    "showSplashHero": true,
    "ctaButtonHeight": 60,
    "endHeroYPosition": 1.05,
    "actionButtonWidth": 350,
    "scoreBoxTopMargin": 0.1,
    "actionButtonHeight": 60,
    "ctaButtonTopMargin": 0.48,
    "instructionBoxYPos": 0.75,
    "logoScalePreloader": 0.4,
    "scoreBoxLeftMargin": 0.9,
    "splashHeroYPosition": 1.05,
    "instructionTopMargin": 0.25,
    "actionButtonTopMargin": 0.45,
    "characterBottomMargin": 0.8
  },
  "gameplay": {
    "lives": 3,
    "carScale": 0.6,
    "duration": 30000,
    "coinScale": 0.4,
    "coinValue": 15,
    "heroScale": 1.1,
    "itemSpeed": 18,
    "logoScale": 0.4,
    "roadScale": 0.6,
    "roadSpeed": 5,
    "enableDrag": false,
    "scaleFactor": 1.4,
    "targetScore": 30,
    "autoEndTimer": false,
    "coinSpawnMax": 1400,
    "coinSpawnMin": 600,
    "logoScaleEnd": 0.6,
    "restartDelay": 1000,
    "blinkDuration": 700,
    "carTitleScale": 1.54,
    "enemySpawnMax": 1500,
    "enemySpawnMin": 1000,
    "laneTiltAngle": 0.2,
    "obstacleScale": 0.6,
    "spawnInterval": 1000,
    "characterScale": 0.6,
    "characterSpeed": 150,
    "finishLineScale": 0.4,
    "collectibleScale": 0.4,
    "collisionEnabled": true,
    "collisionPenalty": 10,
    "finishLineOffset": 1000,
    "leftLanePosition": 0.345,
    "collisionBehavior": "penalty",
    "rightLanePosition": 0.655,
    "laneSwitchDuration": 150,
    "instructionBoxColor": "#0009ff",
    "enemySpeedMultiplier": 0.85,
    "obstacleContainerSize": 291,
    "characterContainerSize": 291,
    "collectibleContainerSize": 97
  },
  "scoreBox": {
    "scale": 1,
    "shape": "circle",
    "textColor": "#FFFFFF",
    "borderColor": "#FFFFFF",
    "borderWidth": 6,
    "backgroundColor": "#0009ff"
  },
  "tracking": {
    "events": {
      "click": {
        "urls": []
      },
      "howToPlay": {
        "urls": [],
        "internalUrls": []
      },
      "impression": {
        "urls": []
      },
      "playableStart": {
        "urls": [],
        "internalUrls": []
      },
      "playableComplete": {
        "urls": [],
        "internalUrls": []
      }
    },
    "ctaClickUrl": "",
    "impressionUrl": "",
    "gameCompleteUrl": "",
    "startPlayableUrl": ""
  },
  "ctaButton": {
    "scale": 1,
    "shape": "pill",
    "textColor": "#FFFFFF",
    "borderColor": "#FFFFFF",
    "borderWidth": 4,
    "backgroundColor": "#DD2024"
  },
  "background": {
    "type": "image",
    "solidColor": "#0009ff",
    "gradientEnd": "#0007cc",
    "gradientAngle": 90,
    "gradientStart": "#0009ff"
  },
  "loadingBar": {
    "width": 250,
    "height": 20,
    "fillColor": "#FBCE0C",
    "backgroundColor": "#333333"
  },
  "transition": {
    "fade": {
      "alpha": 0.8,
      "color": 16502284
    },
    "type": "confetti",
    "confetti": {
      "bursts": 2,
      "origin": {
        "y": 0.6
      },
      "spread": 100,
      "burstDelay": 200,
      "particleCount": 100
    },
    "duration": 1000
  },
  "_editorMode": "advanced",
  "assetScales": {
    "logo": 0.55,
    "endHero": 1,
    "obstacle": 1,
    "scoreBox": 1,
    "character": 1,
    "background": 1,
    "splashHero": 1.35,
    "collectible": 1
  },
  "actionButton": {
    "scale": 0.95,
    "shape": "pill",
    "textColor": "#FFFFFF",
    "borderColor": "#000000",
    "borderWidth": 8,
    "backgroundColor": "#fcb828"
  },
  "firstPartyData": {
    "enabled": true,
    "screens": {
      "age": true,
      "email": false,
      "gender": false
    },
    "placement": "midGame",
    "emailPromptText": ""
  }
};
