/**
 * GAME CONFIGURATION
 * Auto-generated by Playable Creator Studio
 */

window.GAME_CONFIG = {
  "cta": {
    "url": "https://aura.com",
    "target": "_blank"
  },
  "text": {
    "ctaSize": 36,
    "ctaText": "BUYYYY",
    "endTitle": "You did it!",
    "scoreSize": 40,
    "howToTitle": "HOW TO PLAY",
    "scoreColor": "#FFFFFF",
    "endSubtitle": "Ready for more?",
    "howToAction": "TAP TO START",
    "instruction": "Match items\nto win!",
    "scoreFormat": "{score}/{target}",
    "endTitleSize": 80,
    "endTitleColor": "#dfab2e",
    "matchMessages": [
      "Great match!",
      "Keep going!",
      "Awesome!",
      "Nice one!",
      "Perfect!"
    ],
    "howToTitleSize": 50,
    "subInstruction": "Swipe to match 3 or more",
    "endSubtitleSize": 40,
    "howToActionSize": 36,
    "howToTitleColor": "#dfab2e",
    "instructionSize": 80,
    "actionButtonSize": 36,
    "actionButtonText": "PLAY GAME",
    "endSubtitleColor": "#FFFFFF",
    "howToActionColor": "#dfab2e",
    "howToInstruction": "Swipe to swap items",
    "instructionColor": "#665442",
    "matchMessageSize": 35,
    "matchMessageColor": "#FFFFFF",
    "subInstructionSize": 40,
    "subInstructionColor": "#FFFFFF",
    "howToInstructionSize": 32,
    "howToInstructionColor": "#FFFFFF"
  },
  "fonts": {
    "ctaSize": 36,
    "primary": "Poppins",
    "semibold": "Poppins",
    "scoreSize": 40,
    "scaleFactor": 1,
    "instructionSize": 80,
    "actionButtonSize": 36
  },
  "assets": {
    "grid": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/grid.png",
    "hand": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/hand.png",
    "logo": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/logo.png",
    "item1": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/items/item1.png",
    "item2": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/items/item2.png",
    "item3": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/items/item3.png",
    "item4": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/items/item4.png",
    "item5": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/items/item5.png",
    "item6": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/items/item6.png",
    "endHero": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/endHero.png",
    "gridCell": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/gridCell.png",
    "matchSound": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/audio/match.mp3",
    "playButton": "",
    "splashHero": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/splashHero.png",
    "swipeSound": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/audio/swipe.mp3",
    "progressCap": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/cap.png",
    "howToPlayGif": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/howtoplay.gif",
    "completeSound": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/audio/complete.mp3",
    "ctaButtonImage": "",
    "itemFrameWidth": 100,
    "progressScroll": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/scroll.png",
    "itemFrameHeight": 100,
    "itemsSpritesheet": "",
    "age1": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/fpd/age1.png",
    "age2": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/fpd/age2.png",
    "age3": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/fpd/age3.png",
    "age4": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/fpd/age4.png",
    "age5": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/fpd/age5.png",
    "age6": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/fpd/age6.png",
    "genderMale": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/fpd/genderMale.png",
    "genderFemale": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/fpd/genderFemale.png",
    "genderOthers": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/fpd/genderOthers.png",
    "dataCaptureBg": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Feb/agency_test_001/match_3_basic_test_c54656cd/assets/images/fpd/background.png"
  },
  "canvas": {
    "width": 960,
    "height": 1440,
    "backgroundColor": "#ce3b2e"
  },
  "layout": {
    "gridScale": 1,
    "logoScale": 0.5,
    "gridCenterY": 0.55,
    "scaleFactor": 1,
    "showEndHero": true,
    "logoScaleEnd": 0.5,
    "logoScaleGame": 0.4,
    "logoTopMargin": 0.05,
    "logoYPosition": 0.05,
    "ctaButtonWidth": 400,
    "showSplashHero": true,
    "ctaButtonHeight": 80,
    "endHeroYPosition": 0.55,
    "progressBarWidth": 0.8,
    "actionButtonWidth": 480,
    "howToOverlayAlpha": 0.9,
    "actionButtonHeight": 96,
    "ctaButtonTopMargin": 0.85,
    "logoScalePreloader": 0.4,
    "splashHeroYPosition": 0.55,
    "instructionTopMargin": 0.25,
    "progressBarTopMargin": 0.88,
    "actionButtonTopMargin": 0.85,
    "matchMessageTopMargin": 0.22
  },
  "gameplay": {
    "gridSize": 4,
    "itemSize": 100,
    "fallSpeed": 125,
    "itemSpeed": 125,
    "itemTypes": 4,
    "swapSpeed": 200,
    "enableDrag": true,
    "matchTarget": 3,
    "targetScore": 3,
    "autoEndTimer": false,
    "destroySpeed": 200,
    "enableSounds": true,
    "gameDuration": 30000,
    "spawnInterval": 1000,
    "characterScale": 1,
    "characterSpeed": 200,
    "minMatchLength": 3,
    "collectibleScale": 1
  },
  "scoreBox": {
    "scale": 1,
    "shape": "rounded",
    "textColor": "#FFFFFF",
    "borderColor": "#dfab2e",
    "borderWidth": 0,
    "backgroundColor": "#665442"
  },
  "tracking": {
    "events": {
      "click": {
        "urls": []
      },
      "match1": {
        "urls": [],
        "internalUrls": []
      },
      "match2": {
        "urls": [],
        "internalUrls": []
      },
      "match3": {
        "urls": [],
        "internalUrls": []
      },
      "howToPlay": {
        "urls": [],
        "internalUrls": []
      },
      "impression": {
        "urls": []
      },
      "playableStart": {
        "urls": [],
        "internalUrls": []
      },
      "playableComplete": {
        "urls": [],
        "internalUrls": []
      }
    },
    "ctaClickUrl": "",
    "impressionUrl": "",
    "gameCompleteUrl": "",
    "startPlayableUrl": ""
  },
  "ctaButton": {
    "scale": 1,
    "shape": "rounded",
    "textColor": "#665442",
    "borderColor": "#665442",
    "borderWidth": 2,
    "backgroundColor": "#ead0bf"
  },
  "howToPlay": {
    "enabled": true,
    "showGif": true,
    "autoSkipDelay": 0
  },
  "background": {
    "type": "solid",
    "image": "",
    "solidColor": "#ead0bf",
    "gradientEnd": "#dfab2e",
    "gradientAngle": 180,
    "gradientStart": "#ce3b2e"
  },
  "loadingBar": {
    "width": 250,
    "height": 20,
    "fillColor": "#dfab2e",
    "backgroundColor": "#8a2820"
  },
  "transition": {
    "fade": {
      "alpha": 0.8,
      "color": 266811
    },
    "type": "confetti",
    "confetti": {
      "bursts": 3,
      "origin": {
        "y": 0.6
      },
      "spread": 100,
      "burstDelay": 200,
      "particleCount": 100
    },
    "duration": 2000
  },
  "_editorMode": "basic",
  "assetScales": {
    "grid": 1,
    "hand": 0.25,
    "item": 1,
    "logo": 0.7,
    "endHero": 2,
    "background": 1,
    "splashHero": 1.3,
    "progressCap": 1,
    "progressScroll": 1
  },
  "progressBar": {
    "height": 20,
    "fillColor": "#dfab2e",
    "borderRadius": 10,
    "backgroundColor": "#FFFFFF",
    "showDecorations": false
  },
  "actionButton": {
    "scale": 1,
    "shape": "rounded",
    "textColor": "#ead0bf",
    "borderColor": "#665442",
    "borderWidth": 0,
    "backgroundColor": "#665442"
  },
  "firstPartyData": {
    "enabled": true,
    "screens": {
      "age": true,
      "email": true,
      "gender": true
    },
    "placement": "afterSplash",
    "emailPromptText": "Enter your email for updates"
  }
};
