/**
 * GAME CONFIGURATION
 * Auto-generated by Playable Creator Studio
 */

window.GAME_CONFIG = {
  "cta": {
    "url": "https://example.com",
    "target": "_blank"
  },
  "text": {
    "ctaSize": 60,
    "ctaText": "SHOP NOW",
    "scoreSize": 50,
    "scoreColor": "#000000",
    "instruction": "Catch all the candies!",
    "scoreFormat": "{score} / {target}",
    "instructionSize": 50,
    "actionButtonSize": 60,
    "actionButtonText": "TAP TO PLAY",
    "instructionColor": "#6adcef"
  },
  "fonts": {
    "ctaSize": 40,
    "primary": "Poppins",
    "semibold": "PoppinsSemiBold",
    "scoreSize": 36,
    "scaleFactor": 1.4,
    "instructionSize": 50,
    "actionButtonSize": 32
  },
  "assets": {
    "age1": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/fpd/age1.png",
    "age2": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/fpd/age2.png",
    "age3": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/fpd/age3.png",
    "age4": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/fpd/age4.png",
    "age5": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/fpd/age5.png",
    "age6": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/fpd/age6.png",
    "logo": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/logo.png",
    "endHero": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/endHero.png",
    "scoreBox": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/score-box.png",
    "character": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/character.png",
    "background": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/background.png",
    "genderMale": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/fpd/genderMale.png",
    "splashHero": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/splash-hero.png",
    "collectible": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/collectible.png",
    "collectSound": "",
    "genderFemale": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/fpd/genderFemale.png",
    "genderOthers": "https://creativehubiion.github.io/advertiser-creatives/finalbuildfiles/studio/2026/Jan/agency_test_001/mcd_playable_f669f32e/assets/images/fpd/genderOthers.png",
    "backgroundMusic": ""
  },
  "canvas": {
    "width": 1280,
    "height": 1920,
    "backgroundColor": "#ce325d"
  },
  "layout": {
    "logoScale": 1.2,
    "scaleFactor": 1.4,
    "showEndHero": true,
    "logoScaleEnd": 1.2,
    "logoScaleGame": 0.5,
    "logoTopMargin": 0.16,
    "scoreBoxScale": 1.68,
    "ctaButtonWidth": 400,
    "showSplashHero": true,
    "ctaButtonHeight": 100,
    "endHeroYPosition": 0.55,
    "actionButtonWidth": 400,
    "scoreBoxTopMargin": 0.1,
    "actionButtonHeight": 100,
    "ctaButtonTopMargin": 0.85,
    "logoScalePreloader": 0.8,
    "scoreBoxLeftMargin": 0.15,
    "splashHeroYPosition": 0.55,
    "instructionTopMargin": 0.45,
    "actionButtonTopMargin": 0.85,
    "characterBottomMargin": 0.1
  },
  "gameplay": {
    "itemSpeed": 10,
    "enableDrag": true,
    "targetScore": 10,
    "autoEndTimer": false,
    "gameDuration": 30000,
    "spawnInterval": 1200,
    "characterScale": 1.12,
    "characterSpeed": 20,
    "collectibleScale": 0.875
  },
  "scoreBox": {
    "scale": 1,
    "shape": "pill",
    "textColor": "#000000",
    "borderColor": "#6adcef",
    "borderWidth": 0,
    "backgroundColor": "#6adcef"
  },
  "tracking": {
    "events": {
      "click": {
        "urls": []
      },
      "howToPlay": {
        "urls": [],
        "internalUrls": [
          "https://staging-dmp-producer.iion.io/tracker/impressions?platform=RTB&campaign_id=%%campaignId%%&publisher_id=%%pubId%%&creative_id=%%creativeId%%&request_id=%%requestId%%&user_id=%%userId%%&ip_address=%%ip%%&app_id_bundle_id=%%bundle%%&maid=%%ifa%%&app_name=%%appName%%&os=%%os%%&user_agent=%%userAgentEnc%%&latitude=%%lat%%&longitude=%%lon%%&page_url=%%pageUrl%%&country=%%country%%&device_make=%%deviceMake%%&domain=%%domain%%&height=%%height%%&width=%%width%%&video_min_duration=%%videoMinDuration%%&video_max_duration=%%videoMaxDuration%%&content_genre=%%contgenre%%&content_cat=%%contcat%%&gdpr=%%gdpr%%&gdpr_consent=%%gdprConsent%%&demand_id=%%demandId%%&line_item=%%adgroupId%%&event_name=how_to_play"
        ]
      },
      "impression": {
        "urls": []
      },
      "playableStart": {
        "urls": [],
        "internalUrls": [
          "https://staging-dmp-producer.iion.io/tracker/impressions?platform=RTB&campaign_id=%%campaignId%%&publisher_id=%%pubId%%&creative_id=%%creativeId%%&request_id=%%requestId%%&user_id=%%userId%%&ip_address=%%ip%%&app_id_bundle_id=%%bundle%%&maid=%%ifa%%&app_name=%%appName%%&os=%%os%%&user_agent=%%userAgentEnc%%&latitude=%%lat%%&longitude=%%lon%%&page_url=%%pageUrl%%&country=%%country%%&device_make=%%deviceMake%%&domain=%%domain%%&height=%%height%%&width=%%width%%&video_min_duration=%%videoMinDuration%%&video_max_duration=%%videoMaxDuration%%&content_genre=%%contgenre%%&content_cat=%%contcat%%&gdpr=%%gdpr%%&gdpr_consent=%%gdprConsent%%&demand_id=%%demandId%%&line_item=%%adgroupId%%&event_name=playable_start"
        ]
      },
      "playableComplete": {
        "urls": [],
        "internalUrls": [
          "https://staging-dmp-producer.iion.io/tracker/impressions?platform=RTB&campaign_id=%%campaignId%%&publisher_id=%%pubId%%&creative_id=%%creativeId%%&request_id=%%requestId%%&user_id=%%userId%%&ip_address=%%ip%%&app_id_bundle_id=%%bundle%%&maid=%%ifa%%&app_name=%%appName%%&os=%%os%%&user_agent=%%userAgentEnc%%&latitude=%%lat%%&longitude=%%lon%%&page_url=%%pageUrl%%&country=%%country%%&device_make=%%deviceMake%%&domain=%%domain%%&height=%%height%%&width=%%width%%&video_min_duration=%%videoMinDuration%%&video_max_duration=%%videoMaxDuration%%&content_genre=%%contgenre%%&content_cat=%%contcat%%&gdpr=%%gdpr%%&gdpr_consent=%%gdprConsent%%&demand_id=%%demandId%%&line_item=%%adgroupId%%&event_name=playable_complete"
        ]
      }
    },
    "ctaClickUrl": "",
    "impressionUrl": "",
    "gameCompleteUrl": "",
    "startPlayableUrl": ""
  },
  "ctaButton": {
    "scale": 1,
    "shape": "rounded",
    "textColor": "#ce325d",
    "borderColor": "#6adcef",
    "borderWidth": 0,
    "backgroundColor": "#6adcef"
  },
  "background": {
    "type": "solid",
    "image": "assets/images/background.png",
    "solidColor": "#ce325d",
    "gradientEnd": "#6adcef",
    "gradientAngle": 180,
    "gradientStart": "#ce325d"
  },
  "loadingBar": {
    "width": 400,
    "height": 20,
    "fillColor": "#6adcef",
    "backgroundColor": "#8B1E3F"
  },
  "transition": {
    "fade": {
      "alpha": 0.8,
      "color": 16777215
    },
    "type": "confetti",
    "confetti": {
      "bursts": 3,
      "origin": {
        "y": 0.6
      },
      "spread": 100,
      "burstDelay": 200,
      "particleCount": 150
    },
    "duration": 2000
  },
  "_editorMode": "basic",
  "assetScales": {
    "logo": 0.8,
    "endHero": 1,
    "scoreBox": 1,
    "character": 1,
    "background": 1,
    "splashHero": 1,
    "collectible": 1
  },
  "actionButton": {
    "scale": 1,
    "shape": "rounded",
    "textColor": "#ce325d",
    "borderColor": "#6adcef",
    "borderWidth": 0,
    "backgroundColor": "#6adcef"
  },
  "firstPartyData": {
    "enabled": false,
    "screens": {
      "age": false,
      "email": false,
      "gender": false
    },
    "placement": null,
    "emailPromptText": ""
  }
};
